site_name: "MkDocs Material Devcontainer"
repo_url: https://github.com/niclasheinz/mkdocs-material-devcontainer
site_author: Niclas Heinz
repo_name: niclasheinz/mkdocs-material-devcontainer 
site_url: https://mydomain.org/mysite
theme:
  name: material